atom_filter: -1
batch_size: 40
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: PCQM4MV2
dataset_arg: null
dataset_root: ./datasets/PCQM4MV2
derivative: false
distributed_backend: ddp
early_stopping_patience: 150
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
energy_files: null
energy_weight: 0.0
force_files: null
force_weight: 1.0
inference_batch_size: 50
load_model: null
log_dir: ./experiments/AniDS/
lr: 0.0004
lr_schedule: cosine
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 15
lr_warmup_steps: 4000
lr_cosine_length: 400000
max_num_neighbors: 32
max_z: 100
ngpus: -1
num_epochs: 16
num_steps: 400000
num_nodes: 1
num_workers: 10
precision: 32
redirect: false
reduce_op: add
save_interval: 1
splits: null
standardize: false
test_interval: 1
test_size: 100
train_size: null
val_size: 100
weight_decay: 0.0
position_noise_scale: 0.04
denoising_weight: 1.0
denoising_only: true
wandb_notes: ""
job_id: auto

name: equiformer_md17_dens_vae
irreps_in:                  '64x0e'
irreps_equivariant_inputs:  '1x0e+1x1e+1x2e'          # for encoding forces during denoising positions
irreps_node_embedding:      '128x0e+64x1e+32x2e'
num_layers:                 6
irreps_node_attr:           '1x0e' 
irreps_sh:                  '1x0e+1x1e+1x2e'
max_radius:                 5.0
number_of_basis:            32
basis_type:                 'exp' 
fc_neurons:                 [64, 64]
irreps_feature:             '512x0e+256x1e+128x2e'    # increase by 4 times      
irreps_head:                '32x0e+16x1e+8x2e' 
num_heads:                  4 
irreps_pre_attn:            '128x0e+64x1e+32x2e'
rescale_degree:             False
nonlinear_message:          True
irreps_mlp_mid:             '384x0e+192x1e+96x2e'
norm_layer:                 'layer'
alpha_drop:                 0.0 
proj_drop:                  0.0 
out_drop:                   0.0
drop_path_rate:             0.0
use_force_encoding:         True
